spring:
  application:
    name: expenses

  datasource:
    url: jdbc:h2:mem:expenses;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: none  # Since we're using Liquibase for schema management
    show-sql: true    # Useful for development
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
